/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 18 December, 2023 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.41.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20039UpgradeWindow Upgrade window for devices in network
type InlineResponse20039UpgradeWindow struct {
	// Day of the week
	DayOfWeek *string `json:"dayOfWeek,omitempty"`
	// Hour of the day
	HourOfDay *string `json:"hourOfDay,omitempty"`
}

// NewInlineResponse20039UpgradeWindow instantiates a new InlineResponse20039UpgradeWindow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20039UpgradeWindow() *InlineResponse20039UpgradeWindow {
	this := InlineResponse20039UpgradeWindow{}
	return &this
}

// NewInlineResponse20039UpgradeWindowWithDefaults instantiates a new InlineResponse20039UpgradeWindow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20039UpgradeWindowWithDefaults() *InlineResponse20039UpgradeWindow {
	this := InlineResponse20039UpgradeWindow{}
	return &this
}

// GetDayOfWeek returns the DayOfWeek field value if set, zero value otherwise.
func (o *InlineResponse20039UpgradeWindow) GetDayOfWeek() string {
	if o == nil || isNil(o.DayOfWeek) {
		var ret string
		return ret
	}
	return *o.DayOfWeek
}

// GetDayOfWeekOk returns a tuple with the DayOfWeek field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20039UpgradeWindow) GetDayOfWeekOk() (*string, bool) {
	if o == nil || isNil(o.DayOfWeek) {
    return nil, false
	}
	return o.DayOfWeek, true
}

// HasDayOfWeek returns a boolean if a field has been set.
func (o *InlineResponse20039UpgradeWindow) HasDayOfWeek() bool {
	if o != nil && !isNil(o.DayOfWeek) {
		return true
	}

	return false
}

// SetDayOfWeek gets a reference to the given string and assigns it to the DayOfWeek field.
func (o *InlineResponse20039UpgradeWindow) SetDayOfWeek(v string) {
	o.DayOfWeek = &v
}

// GetHourOfDay returns the HourOfDay field value if set, zero value otherwise.
func (o *InlineResponse20039UpgradeWindow) GetHourOfDay() string {
	if o == nil || isNil(o.HourOfDay) {
		var ret string
		return ret
	}
	return *o.HourOfDay
}

// GetHourOfDayOk returns a tuple with the HourOfDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20039UpgradeWindow) GetHourOfDayOk() (*string, bool) {
	if o == nil || isNil(o.HourOfDay) {
    return nil, false
	}
	return o.HourOfDay, true
}

// HasHourOfDay returns a boolean if a field has been set.
func (o *InlineResponse20039UpgradeWindow) HasHourOfDay() bool {
	if o != nil && !isNil(o.HourOfDay) {
		return true
	}

	return false
}

// SetHourOfDay gets a reference to the given string and assigns it to the HourOfDay field.
func (o *InlineResponse20039UpgradeWindow) SetHourOfDay(v string) {
	o.HourOfDay = &v
}

func (o InlineResponse20039UpgradeWindow) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.DayOfWeek) {
		toSerialize["dayOfWeek"] = o.DayOfWeek
	}
	if !isNil(o.HourOfDay) {
		toSerialize["hourOfDay"] = o.HourOfDay
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20039UpgradeWindow struct {
	value *InlineResponse20039UpgradeWindow
	isSet bool
}

func (v NullableInlineResponse20039UpgradeWindow) Get() *InlineResponse20039UpgradeWindow {
	return v.value
}

func (v *NullableInlineResponse20039UpgradeWindow) Set(val *InlineResponse20039UpgradeWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20039UpgradeWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20039UpgradeWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20039UpgradeWindow(val *InlineResponse20039UpgradeWindow) *NullableInlineResponse20039UpgradeWindow {
	return &NullableInlineResponse20039UpgradeWindow{value: val, isSet: true}
}

func (v NullableInlineResponse20039UpgradeWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20039UpgradeWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


