/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 February, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.43.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200115NamedVlans Named VLAN settings for wireless networks.
type InlineResponse200115NamedVlans struct {
	PoolDhcpMonitoring *InlineResponse200115NamedVlansPoolDhcpMonitoring `json:"poolDhcpMonitoring,omitempty"`
}

// NewInlineResponse200115NamedVlans instantiates a new InlineResponse200115NamedVlans object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200115NamedVlans() *InlineResponse200115NamedVlans {
	this := InlineResponse200115NamedVlans{}
	return &this
}

// NewInlineResponse200115NamedVlansWithDefaults instantiates a new InlineResponse200115NamedVlans object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200115NamedVlansWithDefaults() *InlineResponse200115NamedVlans {
	this := InlineResponse200115NamedVlans{}
	return &this
}

// GetPoolDhcpMonitoring returns the PoolDhcpMonitoring field value if set, zero value otherwise.
func (o *InlineResponse200115NamedVlans) GetPoolDhcpMonitoring() InlineResponse200115NamedVlansPoolDhcpMonitoring {
	if o == nil || isNil(o.PoolDhcpMonitoring) {
		var ret InlineResponse200115NamedVlansPoolDhcpMonitoring
		return ret
	}
	return *o.PoolDhcpMonitoring
}

// GetPoolDhcpMonitoringOk returns a tuple with the PoolDhcpMonitoring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200115NamedVlans) GetPoolDhcpMonitoringOk() (*InlineResponse200115NamedVlansPoolDhcpMonitoring, bool) {
	if o == nil || isNil(o.PoolDhcpMonitoring) {
    return nil, false
	}
	return o.PoolDhcpMonitoring, true
}

// HasPoolDhcpMonitoring returns a boolean if a field has been set.
func (o *InlineResponse200115NamedVlans) HasPoolDhcpMonitoring() bool {
	if o != nil && !isNil(o.PoolDhcpMonitoring) {
		return true
	}

	return false
}

// SetPoolDhcpMonitoring gets a reference to the given InlineResponse200115NamedVlansPoolDhcpMonitoring and assigns it to the PoolDhcpMonitoring field.
func (o *InlineResponse200115NamedVlans) SetPoolDhcpMonitoring(v InlineResponse200115NamedVlansPoolDhcpMonitoring) {
	o.PoolDhcpMonitoring = &v
}

func (o InlineResponse200115NamedVlans) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PoolDhcpMonitoring) {
		toSerialize["poolDhcpMonitoring"] = o.PoolDhcpMonitoring
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200115NamedVlans struct {
	value *InlineResponse200115NamedVlans
	isSet bool
}

func (v NullableInlineResponse200115NamedVlans) Get() *InlineResponse200115NamedVlans {
	return v.value
}

func (v *NullableInlineResponse200115NamedVlans) Set(val *InlineResponse200115NamedVlans) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200115NamedVlans) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200115NamedVlans) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200115NamedVlans(val *InlineResponse200115NamedVlans) *NullableInlineResponse200115NamedVlans {
	return &NullableInlineResponse200115NamedVlans{value: val, isSet: true}
}

func (v NullableInlineResponse200115NamedVlans) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200115NamedVlans) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


