/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 04 June, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.59.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject289 struct for InlineObject289
type InlineObject289 struct {
	// Boolean for updating SAML SSO enabled settings.
	Enabled *bool `json:"enabled,omitempty"`
}

// NewInlineObject289 instantiates a new InlineObject289 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject289() *InlineObject289 {
	this := InlineObject289{}
	return &this
}

// NewInlineObject289WithDefaults instantiates a new InlineObject289 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject289WithDefaults() *InlineObject289 {
	this := InlineObject289{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *InlineObject289) GetEnabled() bool {
	if o == nil || isNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject289) GetEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.Enabled) {
    return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *InlineObject289) HasEnabled() bool {
	if o != nil && !isNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *InlineObject289) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o InlineObject289) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject289 struct {
	value *InlineObject289
	isSet bool
}

func (v NullableInlineObject289) Get() *InlineObject289 {
	return v.value
}

func (v *NullableInlineObject289) Set(val *InlineObject289) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject289) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject289) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject289(val *InlineObject289) *NullableInlineObject289 {
	return &NullableInlineObject289{value: val, isSet: true}
}

func (v NullableInlineObject289) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject289) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


