/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 November, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.64.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200160 struct for InlineResponse200160
type InlineResponse200160 struct {
	// An array of DSCP to CoS mappings. An empty array will reset the mappings to default.
	Mappings []InlineResponse200160Mappings `json:"mappings,omitempty"`
}

// NewInlineResponse200160 instantiates a new InlineResponse200160 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200160() *InlineResponse200160 {
	this := InlineResponse200160{}
	return &this
}

// NewInlineResponse200160WithDefaults instantiates a new InlineResponse200160 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200160WithDefaults() *InlineResponse200160 {
	this := InlineResponse200160{}
	return &this
}

// GetMappings returns the Mappings field value if set, zero value otherwise.
func (o *InlineResponse200160) GetMappings() []InlineResponse200160Mappings {
	if o == nil || isNil(o.Mappings) {
		var ret []InlineResponse200160Mappings
		return ret
	}
	return o.Mappings
}

// GetMappingsOk returns a tuple with the Mappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200160) GetMappingsOk() ([]InlineResponse200160Mappings, bool) {
	if o == nil || isNil(o.Mappings) {
    return nil, false
	}
	return o.Mappings, true
}

// HasMappings returns a boolean if a field has been set.
func (o *InlineResponse200160) HasMappings() bool {
	if o != nil && !isNil(o.Mappings) {
		return true
	}

	return false
}

// SetMappings gets a reference to the given []InlineResponse200160Mappings and assigns it to the Mappings field.
func (o *InlineResponse200160) SetMappings(v []InlineResponse200160Mappings) {
	o.Mappings = v
}

func (o InlineResponse200160) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Mappings) {
		toSerialize["mappings"] = o.Mappings
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200160 struct {
	value *InlineResponse200160
	isSet bool
}

func (v NullableInlineResponse200160) Get() *InlineResponse200160 {
	return v.value
}

func (v *NullableInlineResponse200160) Set(val *InlineResponse200160) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200160) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200160) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200160(val *InlineResponse200160) *NullableInlineResponse200160 {
	return &NullableInlineResponse200160{value: val, isSet: true}
}

func (v NullableInlineResponse200160) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200160) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


