/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 May, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.46.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject257 struct for InlineObject257
type InlineObject257 struct {
	// Sentry Group Policies for the Organization keyed by Network Id
	Items []OrganizationsOrganizationIdSmSentryPoliciesAssignmentsItems `json:"items"`
}

// NewInlineObject257 instantiates a new InlineObject257 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject257(items []OrganizationsOrganizationIdSmSentryPoliciesAssignmentsItems) *InlineObject257 {
	this := InlineObject257{}
	this.Items = items
	return &this
}

// NewInlineObject257WithDefaults instantiates a new InlineObject257 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject257WithDefaults() *InlineObject257 {
	this := InlineObject257{}
	return &this
}

// GetItems returns the Items field value
func (o *InlineObject257) GetItems() []OrganizationsOrganizationIdSmSentryPoliciesAssignmentsItems {
	if o == nil {
		var ret []OrganizationsOrganizationIdSmSentryPoliciesAssignmentsItems
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *InlineObject257) GetItemsOk() ([]OrganizationsOrganizationIdSmSentryPoliciesAssignmentsItems, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *InlineObject257) SetItems(v []OrganizationsOrganizationIdSmSentryPoliciesAssignmentsItems) {
	o.Items = v
}

func (o InlineObject257) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject257 struct {
	value *InlineObject257
	isSet bool
}

func (v NullableInlineObject257) Get() *InlineObject257 {
	return v.value
}

func (v *NullableInlineObject257) Set(val *InlineObject257) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject257) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject257) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject257(val *InlineObject257) *NullableInlineObject257 {
	return &NullableInlineObject257{value: val, isSet: true}
}

func (v NullableInlineObject257) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject257) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


