/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 May, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.58.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200373CountsClients Wireless LAN controller client counts
type InlineResponse200373CountsClients struct {
	ByStatus *InlineResponse200373CountsClientsByStatus `json:"byStatus,omitempty"`
}

// NewInlineResponse200373CountsClients instantiates a new InlineResponse200373CountsClients object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200373CountsClients() *InlineResponse200373CountsClients {
	this := InlineResponse200373CountsClients{}
	return &this
}

// NewInlineResponse200373CountsClientsWithDefaults instantiates a new InlineResponse200373CountsClients object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200373CountsClientsWithDefaults() *InlineResponse200373CountsClients {
	this := InlineResponse200373CountsClients{}
	return &this
}

// GetByStatus returns the ByStatus field value if set, zero value otherwise.
func (o *InlineResponse200373CountsClients) GetByStatus() InlineResponse200373CountsClientsByStatus {
	if o == nil || isNil(o.ByStatus) {
		var ret InlineResponse200373CountsClientsByStatus
		return ret
	}
	return *o.ByStatus
}

// GetByStatusOk returns a tuple with the ByStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200373CountsClients) GetByStatusOk() (*InlineResponse200373CountsClientsByStatus, bool) {
	if o == nil || isNil(o.ByStatus) {
    return nil, false
	}
	return o.ByStatus, true
}

// HasByStatus returns a boolean if a field has been set.
func (o *InlineResponse200373CountsClients) HasByStatus() bool {
	if o != nil && !isNil(o.ByStatus) {
		return true
	}

	return false
}

// SetByStatus gets a reference to the given InlineResponse200373CountsClientsByStatus and assigns it to the ByStatus field.
func (o *InlineResponse200373CountsClients) SetByStatus(v InlineResponse200373CountsClientsByStatus) {
	o.ByStatus = &v
}

func (o InlineResponse200373CountsClients) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ByStatus) {
		toSerialize["byStatus"] = o.ByStatus
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200373CountsClients struct {
	value *InlineResponse200373CountsClients
	isSet bool
}

func (v NullableInlineResponse200373CountsClients) Get() *InlineResponse200373CountsClients {
	return v.value
}

func (v *NullableInlineResponse200373CountsClients) Set(val *InlineResponse200373CountsClients) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200373CountsClients) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200373CountsClients) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200373CountsClients(val *InlineResponse200373CountsClients) *NullableInlineResponse200373CountsClients {
	return &NullableInlineResponse200373CountsClients{value: val, isSet: true}
}

func (v NullableInlineResponse200373CountsClients) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200373CountsClients) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


