/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 April, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.57.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200361Usage The usage on the interfaces of the wireless LAN controller
type InlineResponse200361Usage struct {
	// The total usage on the interface during the interval, unit is bit/sec
	Total *int32 `json:"total,omitempty"`
	// The received usage on the interface during the interval, unit is bit/sec
	Recv *int32 `json:"recv,omitempty"`
	// The sent usage on the interface during the interval, unit is bit/sec
	Send *int32 `json:"send,omitempty"`
}

// NewInlineResponse200361Usage instantiates a new InlineResponse200361Usage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200361Usage() *InlineResponse200361Usage {
	this := InlineResponse200361Usage{}
	return &this
}

// NewInlineResponse200361UsageWithDefaults instantiates a new InlineResponse200361Usage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200361UsageWithDefaults() *InlineResponse200361Usage {
	this := InlineResponse200361Usage{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *InlineResponse200361Usage) GetTotal() int32 {
	if o == nil || isNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200361Usage) GetTotalOk() (*int32, bool) {
	if o == nil || isNil(o.Total) {
    return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *InlineResponse200361Usage) HasTotal() bool {
	if o != nil && !isNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *InlineResponse200361Usage) SetTotal(v int32) {
	o.Total = &v
}

// GetRecv returns the Recv field value if set, zero value otherwise.
func (o *InlineResponse200361Usage) GetRecv() int32 {
	if o == nil || isNil(o.Recv) {
		var ret int32
		return ret
	}
	return *o.Recv
}

// GetRecvOk returns a tuple with the Recv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200361Usage) GetRecvOk() (*int32, bool) {
	if o == nil || isNil(o.Recv) {
    return nil, false
	}
	return o.Recv, true
}

// HasRecv returns a boolean if a field has been set.
func (o *InlineResponse200361Usage) HasRecv() bool {
	if o != nil && !isNil(o.Recv) {
		return true
	}

	return false
}

// SetRecv gets a reference to the given int32 and assigns it to the Recv field.
func (o *InlineResponse200361Usage) SetRecv(v int32) {
	o.Recv = &v
}

// GetSend returns the Send field value if set, zero value otherwise.
func (o *InlineResponse200361Usage) GetSend() int32 {
	if o == nil || isNil(o.Send) {
		var ret int32
		return ret
	}
	return *o.Send
}

// GetSendOk returns a tuple with the Send field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200361Usage) GetSendOk() (*int32, bool) {
	if o == nil || isNil(o.Send) {
    return nil, false
	}
	return o.Send, true
}

// HasSend returns a boolean if a field has been set.
func (o *InlineResponse200361Usage) HasSend() bool {
	if o != nil && !isNil(o.Send) {
		return true
	}

	return false
}

// SetSend gets a reference to the given int32 and assigns it to the Send field.
func (o *InlineResponse200361Usage) SetSend(v int32) {
	o.Send = &v
}

func (o InlineResponse200361Usage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !isNil(o.Recv) {
		toSerialize["recv"] = o.Recv
	}
	if !isNil(o.Send) {
		toSerialize["send"] = o.Send
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200361Usage struct {
	value *InlineResponse200361Usage
	isSet bool
}

func (v NullableInlineResponse200361Usage) Get() *InlineResponse200361Usage {
	return v.value
}

func (v *NullableInlineResponse200361Usage) Set(val *InlineResponse200361Usage) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200361Usage) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200361Usage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200361Usage(val *InlineResponse200361Usage) *NullableInlineResponse200361Usage {
	return &NullableInlineResponse200361Usage{value: val, isSet: true}
}

func (v NullableInlineResponse200361Usage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200361Usage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


