/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 July, 2023 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.35.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200108 struct for InlineResponse200108
type InlineResponse200108 struct {
	ResponseCodeCounts *InlineResponse200108ResponseCodeCounts `json:"responseCodeCounts,omitempty"`
}

// NewInlineResponse200108 instantiates a new InlineResponse200108 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200108() *InlineResponse200108 {
	this := InlineResponse200108{}
	return &this
}

// NewInlineResponse200108WithDefaults instantiates a new InlineResponse200108 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200108WithDefaults() *InlineResponse200108 {
	this := InlineResponse200108{}
	return &this
}

// GetResponseCodeCounts returns the ResponseCodeCounts field value if set, zero value otherwise.
func (o *InlineResponse200108) GetResponseCodeCounts() InlineResponse200108ResponseCodeCounts {
	if o == nil || isNil(o.ResponseCodeCounts) {
		var ret InlineResponse200108ResponseCodeCounts
		return ret
	}
	return *o.ResponseCodeCounts
}

// GetResponseCodeCountsOk returns a tuple with the ResponseCodeCounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200108) GetResponseCodeCountsOk() (*InlineResponse200108ResponseCodeCounts, bool) {
	if o == nil || isNil(o.ResponseCodeCounts) {
    return nil, false
	}
	return o.ResponseCodeCounts, true
}

// HasResponseCodeCounts returns a boolean if a field has been set.
func (o *InlineResponse200108) HasResponseCodeCounts() bool {
	if o != nil && !isNil(o.ResponseCodeCounts) {
		return true
	}

	return false
}

// SetResponseCodeCounts gets a reference to the given InlineResponse200108ResponseCodeCounts and assigns it to the ResponseCodeCounts field.
func (o *InlineResponse200108) SetResponseCodeCounts(v InlineResponse200108ResponseCodeCounts) {
	o.ResponseCodeCounts = &v
}

func (o InlineResponse200108) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ResponseCodeCounts) {
		toSerialize["responseCodeCounts"] = o.ResponseCodeCounts
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200108 struct {
	value *InlineResponse200108
	isSet bool
}

func (v NullableInlineResponse200108) Get() *InlineResponse200108 {
	return v.value
}

func (v *NullableInlineResponse200108) Set(val *InlineResponse200108) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200108) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200108) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200108(val *InlineResponse200108) *NullableInlineResponse200108 {
	return &NullableInlineResponse200108{value: val, isSet: true}
}

func (v NullableInlineResponse200108) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200108) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


