/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 August, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.49.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject213 struct for InlineObject213
type InlineObject213 struct {
	// The list of VPN peers
	Peers []OrganizationsOrganizationIdApplianceVpnThirdPartyVPNPeersPeers `json:"peers"`
}

// NewInlineObject213 instantiates a new InlineObject213 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject213(peers []OrganizationsOrganizationIdApplianceVpnThirdPartyVPNPeersPeers) *InlineObject213 {
	this := InlineObject213{}
	this.Peers = peers
	return &this
}

// NewInlineObject213WithDefaults instantiates a new InlineObject213 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject213WithDefaults() *InlineObject213 {
	this := InlineObject213{}
	return &this
}

// GetPeers returns the Peers field value
func (o *InlineObject213) GetPeers() []OrganizationsOrganizationIdApplianceVpnThirdPartyVPNPeersPeers {
	if o == nil {
		var ret []OrganizationsOrganizationIdApplianceVpnThirdPartyVPNPeersPeers
		return ret
	}

	return o.Peers
}

// GetPeersOk returns a tuple with the Peers field value
// and a boolean to check if the value has been set.
func (o *InlineObject213) GetPeersOk() ([]OrganizationsOrganizationIdApplianceVpnThirdPartyVPNPeersPeers, bool) {
	if o == nil {
    return nil, false
	}
	return o.Peers, true
}

// SetPeers sets field value
func (o *InlineObject213) SetPeers(v []OrganizationsOrganizationIdApplianceVpnThirdPartyVPNPeersPeers) {
	o.Peers = v
}

func (o InlineObject213) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["peers"] = o.Peers
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject213 struct {
	value *InlineObject213
	isSet bool
}

func (v NullableInlineObject213) Get() *InlineObject213 {
	return v.value
}

func (v *NullableInlineObject213) Set(val *InlineObject213) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject213) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject213) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject213(val *InlineObject213) *NullableInlineObject213 {
	return &NullableInlineObject213{value: val, isSet: true}
}

func (v NullableInlineObject213) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject213) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


