/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 May, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.58.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200171 struct for InlineResponse200171
type InlineResponse200171 struct {
	// List of the syslog servers for this network
	Servers []InlineResponse200171Servers `json:"servers,omitempty"`
}

// NewInlineResponse200171 instantiates a new InlineResponse200171 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200171() *InlineResponse200171 {
	this := InlineResponse200171{}
	return &this
}

// NewInlineResponse200171WithDefaults instantiates a new InlineResponse200171 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200171WithDefaults() *InlineResponse200171 {
	this := InlineResponse200171{}
	return &this
}

// GetServers returns the Servers field value if set, zero value otherwise.
func (o *InlineResponse200171) GetServers() []InlineResponse200171Servers {
	if o == nil || isNil(o.Servers) {
		var ret []InlineResponse200171Servers
		return ret
	}
	return o.Servers
}

// GetServersOk returns a tuple with the Servers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200171) GetServersOk() ([]InlineResponse200171Servers, bool) {
	if o == nil || isNil(o.Servers) {
    return nil, false
	}
	return o.Servers, true
}

// HasServers returns a boolean if a field has been set.
func (o *InlineResponse200171) HasServers() bool {
	if o != nil && !isNil(o.Servers) {
		return true
	}

	return false
}

// SetServers gets a reference to the given []InlineResponse200171Servers and assigns it to the Servers field.
func (o *InlineResponse200171) SetServers(v []InlineResponse200171Servers) {
	o.Servers = v
}

func (o InlineResponse200171) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Servers) {
		toSerialize["servers"] = o.Servers
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200171 struct {
	value *InlineResponse200171
	isSet bool
}

func (v NullableInlineResponse200171) Get() *InlineResponse200171 {
	return v.value
}

func (v *NullableInlineResponse200171) Set(val *InlineResponse200171) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200171) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200171) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200171(val *InlineResponse200171) *NullableInlineResponse200171 {
	return &NullableInlineResponse200171{value: val, isSet: true}
}

func (v NullableInlineResponse200171) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200171) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


