/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 October, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.63.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200351WebhookHttpServer The webhook receiver used for the callback webhook
type InlineResponse200351WebhookHttpServer struct {
	// The webhook receiver ID that will receive information
	Id *string `json:"id,omitempty"`
}

// NewInlineResponse200351WebhookHttpServer instantiates a new InlineResponse200351WebhookHttpServer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200351WebhookHttpServer() *InlineResponse200351WebhookHttpServer {
	this := InlineResponse200351WebhookHttpServer{}
	return &this
}

// NewInlineResponse200351WebhookHttpServerWithDefaults instantiates a new InlineResponse200351WebhookHttpServer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200351WebhookHttpServerWithDefaults() *InlineResponse200351WebhookHttpServer {
	this := InlineResponse200351WebhookHttpServer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InlineResponse200351WebhookHttpServer) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200351WebhookHttpServer) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InlineResponse200351WebhookHttpServer) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InlineResponse200351WebhookHttpServer) SetId(v string) {
	o.Id = &v
}

func (o InlineResponse200351WebhookHttpServer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200351WebhookHttpServer struct {
	value *InlineResponse200351WebhookHttpServer
	isSet bool
}

func (v NullableInlineResponse200351WebhookHttpServer) Get() *InlineResponse200351WebhookHttpServer {
	return v.value
}

func (v *NullableInlineResponse200351WebhookHttpServer) Set(val *InlineResponse200351WebhookHttpServer) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200351WebhookHttpServer) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200351WebhookHttpServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200351WebhookHttpServer(val *InlineResponse200351WebhookHttpServer) *NullableInlineResponse200351WebhookHttpServer {
	return &NullableInlineResponse200351WebhookHttpServer{value: val, isSet: true}
}

func (v NullableInlineResponse200351WebhookHttpServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200351WebhookHttpServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


