/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 February, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.43.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20094UplinkClientSampling Uplink client sampling
type InlineResponse20094UplinkClientSampling struct {
	// Enable client sampling on uplink
	Enabled *bool `json:"enabled,omitempty"`
}

// NewInlineResponse20094UplinkClientSampling instantiates a new InlineResponse20094UplinkClientSampling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20094UplinkClientSampling() *InlineResponse20094UplinkClientSampling {
	this := InlineResponse20094UplinkClientSampling{}
	return &this
}

// NewInlineResponse20094UplinkClientSamplingWithDefaults instantiates a new InlineResponse20094UplinkClientSampling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20094UplinkClientSamplingWithDefaults() *InlineResponse20094UplinkClientSampling {
	this := InlineResponse20094UplinkClientSampling{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *InlineResponse20094UplinkClientSampling) GetEnabled() bool {
	if o == nil || isNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20094UplinkClientSampling) GetEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.Enabled) {
    return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *InlineResponse20094UplinkClientSampling) HasEnabled() bool {
	if o != nil && !isNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *InlineResponse20094UplinkClientSampling) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o InlineResponse20094UplinkClientSampling) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20094UplinkClientSampling struct {
	value *InlineResponse20094UplinkClientSampling
	isSet bool
}

func (v NullableInlineResponse20094UplinkClientSampling) Get() *InlineResponse20094UplinkClientSampling {
	return v.value
}

func (v *NullableInlineResponse20094UplinkClientSampling) Set(val *InlineResponse20094UplinkClientSampling) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20094UplinkClientSampling) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20094UplinkClientSampling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20094UplinkClientSampling(val *InlineResponse20094UplinkClientSampling) *NullableInlineResponse20094UplinkClientSampling {
	return &NullableInlineResponse20094UplinkClientSampling{value: val, isSet: true}
}

func (v NullableInlineResponse20094UplinkClientSampling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20094UplinkClientSampling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


