/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 06 August, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.61.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200388ByCore struct for InlineResponse200388ByCore
type InlineResponse200388ByCore struct {
	// The CPU core name
	Name *string `json:"name,omitempty"`
	Usage *InlineResponse200388Usage `json:"usage,omitempty"`
}

// NewInlineResponse200388ByCore instantiates a new InlineResponse200388ByCore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200388ByCore() *InlineResponse200388ByCore {
	this := InlineResponse200388ByCore{}
	return &this
}

// NewInlineResponse200388ByCoreWithDefaults instantiates a new InlineResponse200388ByCore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200388ByCoreWithDefaults() *InlineResponse200388ByCore {
	this := InlineResponse200388ByCore{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InlineResponse200388ByCore) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200388ByCore) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InlineResponse200388ByCore) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InlineResponse200388ByCore) SetName(v string) {
	o.Name = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *InlineResponse200388ByCore) GetUsage() InlineResponse200388Usage {
	if o == nil || isNil(o.Usage) {
		var ret InlineResponse200388Usage
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200388ByCore) GetUsageOk() (*InlineResponse200388Usage, bool) {
	if o == nil || isNil(o.Usage) {
    return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *InlineResponse200388ByCore) HasUsage() bool {
	if o != nil && !isNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given InlineResponse200388Usage and assigns it to the Usage field.
func (o *InlineResponse200388ByCore) SetUsage(v InlineResponse200388Usage) {
	o.Usage = &v
}

func (o InlineResponse200388ByCore) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200388ByCore struct {
	value *InlineResponse200388ByCore
	isSet bool
}

func (v NullableInlineResponse200388ByCore) Get() *InlineResponse200388ByCore {
	return v.value
}

func (v *NullableInlineResponse200388ByCore) Set(val *InlineResponse200388ByCore) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200388ByCore) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200388ByCore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200388ByCore(val *InlineResponse200388ByCore) *NullableInlineResponse200388ByCore {
	return &NullableInlineResponse200388ByCore{value: val, isSet: true}
}

func (v NullableInlineResponse200388ByCore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200388ByCore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


