/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 May, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.58.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200197 struct for InlineResponse200197
type InlineResponse200197 struct {
	// Toggle for enabling or disabling meshing in a network
	MeshingEnabled *bool `json:"meshingEnabled,omitempty"`
	// Toggle for enabling or disabling IPv6 bridging in a network (Note: if enabled, SSIDs must also be configured to use bridge mode)
	Ipv6BridgeEnabled *bool `json:"ipv6BridgeEnabled,omitempty"`
	// Toggle for enabling or disabling location analytics for your network
	LocationAnalyticsEnabled *bool `json:"locationAnalyticsEnabled,omitempty"`
	// The default strategy that network devices will use to perform an upgrade. Requires firmware version MR 26.8 or higher.
	UpgradeStrategy *string `json:"upgradeStrategy,omitempty"`
	// Toggle for enabling or disabling LED lights on all APs in the network (making them run dark)
	LedLightsOn *bool `json:"ledLightsOn,omitempty"`
	NamedVlans *InlineResponse200197NamedVlans `json:"namedVlans,omitempty"`
	RegulatoryDomain *InlineResponse200197RegulatoryDomain `json:"regulatoryDomain,omitempty"`
}

// NewInlineResponse200197 instantiates a new InlineResponse200197 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200197() *InlineResponse200197 {
	this := InlineResponse200197{}
	return &this
}

// NewInlineResponse200197WithDefaults instantiates a new InlineResponse200197 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200197WithDefaults() *InlineResponse200197 {
	this := InlineResponse200197{}
	return &this
}

// GetMeshingEnabled returns the MeshingEnabled field value if set, zero value otherwise.
func (o *InlineResponse200197) GetMeshingEnabled() bool {
	if o == nil || isNil(o.MeshingEnabled) {
		var ret bool
		return ret
	}
	return *o.MeshingEnabled
}

// GetMeshingEnabledOk returns a tuple with the MeshingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200197) GetMeshingEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.MeshingEnabled) {
    return nil, false
	}
	return o.MeshingEnabled, true
}

// HasMeshingEnabled returns a boolean if a field has been set.
func (o *InlineResponse200197) HasMeshingEnabled() bool {
	if o != nil && !isNil(o.MeshingEnabled) {
		return true
	}

	return false
}

// SetMeshingEnabled gets a reference to the given bool and assigns it to the MeshingEnabled field.
func (o *InlineResponse200197) SetMeshingEnabled(v bool) {
	o.MeshingEnabled = &v
}

// GetIpv6BridgeEnabled returns the Ipv6BridgeEnabled field value if set, zero value otherwise.
func (o *InlineResponse200197) GetIpv6BridgeEnabled() bool {
	if o == nil || isNil(o.Ipv6BridgeEnabled) {
		var ret bool
		return ret
	}
	return *o.Ipv6BridgeEnabled
}

// GetIpv6BridgeEnabledOk returns a tuple with the Ipv6BridgeEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200197) GetIpv6BridgeEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.Ipv6BridgeEnabled) {
    return nil, false
	}
	return o.Ipv6BridgeEnabled, true
}

// HasIpv6BridgeEnabled returns a boolean if a field has been set.
func (o *InlineResponse200197) HasIpv6BridgeEnabled() bool {
	if o != nil && !isNil(o.Ipv6BridgeEnabled) {
		return true
	}

	return false
}

// SetIpv6BridgeEnabled gets a reference to the given bool and assigns it to the Ipv6BridgeEnabled field.
func (o *InlineResponse200197) SetIpv6BridgeEnabled(v bool) {
	o.Ipv6BridgeEnabled = &v
}

// GetLocationAnalyticsEnabled returns the LocationAnalyticsEnabled field value if set, zero value otherwise.
func (o *InlineResponse200197) GetLocationAnalyticsEnabled() bool {
	if o == nil || isNil(o.LocationAnalyticsEnabled) {
		var ret bool
		return ret
	}
	return *o.LocationAnalyticsEnabled
}

// GetLocationAnalyticsEnabledOk returns a tuple with the LocationAnalyticsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200197) GetLocationAnalyticsEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.LocationAnalyticsEnabled) {
    return nil, false
	}
	return o.LocationAnalyticsEnabled, true
}

// HasLocationAnalyticsEnabled returns a boolean if a field has been set.
func (o *InlineResponse200197) HasLocationAnalyticsEnabled() bool {
	if o != nil && !isNil(o.LocationAnalyticsEnabled) {
		return true
	}

	return false
}

// SetLocationAnalyticsEnabled gets a reference to the given bool and assigns it to the LocationAnalyticsEnabled field.
func (o *InlineResponse200197) SetLocationAnalyticsEnabled(v bool) {
	o.LocationAnalyticsEnabled = &v
}

// GetUpgradeStrategy returns the UpgradeStrategy field value if set, zero value otherwise.
func (o *InlineResponse200197) GetUpgradeStrategy() string {
	if o == nil || isNil(o.UpgradeStrategy) {
		var ret string
		return ret
	}
	return *o.UpgradeStrategy
}

// GetUpgradeStrategyOk returns a tuple with the UpgradeStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200197) GetUpgradeStrategyOk() (*string, bool) {
	if o == nil || isNil(o.UpgradeStrategy) {
    return nil, false
	}
	return o.UpgradeStrategy, true
}

// HasUpgradeStrategy returns a boolean if a field has been set.
func (o *InlineResponse200197) HasUpgradeStrategy() bool {
	if o != nil && !isNil(o.UpgradeStrategy) {
		return true
	}

	return false
}

// SetUpgradeStrategy gets a reference to the given string and assigns it to the UpgradeStrategy field.
func (o *InlineResponse200197) SetUpgradeStrategy(v string) {
	o.UpgradeStrategy = &v
}

// GetLedLightsOn returns the LedLightsOn field value if set, zero value otherwise.
func (o *InlineResponse200197) GetLedLightsOn() bool {
	if o == nil || isNil(o.LedLightsOn) {
		var ret bool
		return ret
	}
	return *o.LedLightsOn
}

// GetLedLightsOnOk returns a tuple with the LedLightsOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200197) GetLedLightsOnOk() (*bool, bool) {
	if o == nil || isNil(o.LedLightsOn) {
    return nil, false
	}
	return o.LedLightsOn, true
}

// HasLedLightsOn returns a boolean if a field has been set.
func (o *InlineResponse200197) HasLedLightsOn() bool {
	if o != nil && !isNil(o.LedLightsOn) {
		return true
	}

	return false
}

// SetLedLightsOn gets a reference to the given bool and assigns it to the LedLightsOn field.
func (o *InlineResponse200197) SetLedLightsOn(v bool) {
	o.LedLightsOn = &v
}

// GetNamedVlans returns the NamedVlans field value if set, zero value otherwise.
func (o *InlineResponse200197) GetNamedVlans() InlineResponse200197NamedVlans {
	if o == nil || isNil(o.NamedVlans) {
		var ret InlineResponse200197NamedVlans
		return ret
	}
	return *o.NamedVlans
}

// GetNamedVlansOk returns a tuple with the NamedVlans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200197) GetNamedVlansOk() (*InlineResponse200197NamedVlans, bool) {
	if o == nil || isNil(o.NamedVlans) {
    return nil, false
	}
	return o.NamedVlans, true
}

// HasNamedVlans returns a boolean if a field has been set.
func (o *InlineResponse200197) HasNamedVlans() bool {
	if o != nil && !isNil(o.NamedVlans) {
		return true
	}

	return false
}

// SetNamedVlans gets a reference to the given InlineResponse200197NamedVlans and assigns it to the NamedVlans field.
func (o *InlineResponse200197) SetNamedVlans(v InlineResponse200197NamedVlans) {
	o.NamedVlans = &v
}

// GetRegulatoryDomain returns the RegulatoryDomain field value if set, zero value otherwise.
func (o *InlineResponse200197) GetRegulatoryDomain() InlineResponse200197RegulatoryDomain {
	if o == nil || isNil(o.RegulatoryDomain) {
		var ret InlineResponse200197RegulatoryDomain
		return ret
	}
	return *o.RegulatoryDomain
}

// GetRegulatoryDomainOk returns a tuple with the RegulatoryDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200197) GetRegulatoryDomainOk() (*InlineResponse200197RegulatoryDomain, bool) {
	if o == nil || isNil(o.RegulatoryDomain) {
    return nil, false
	}
	return o.RegulatoryDomain, true
}

// HasRegulatoryDomain returns a boolean if a field has been set.
func (o *InlineResponse200197) HasRegulatoryDomain() bool {
	if o != nil && !isNil(o.RegulatoryDomain) {
		return true
	}

	return false
}

// SetRegulatoryDomain gets a reference to the given InlineResponse200197RegulatoryDomain and assigns it to the RegulatoryDomain field.
func (o *InlineResponse200197) SetRegulatoryDomain(v InlineResponse200197RegulatoryDomain) {
	o.RegulatoryDomain = &v
}

func (o InlineResponse200197) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.MeshingEnabled) {
		toSerialize["meshingEnabled"] = o.MeshingEnabled
	}
	if !isNil(o.Ipv6BridgeEnabled) {
		toSerialize["ipv6BridgeEnabled"] = o.Ipv6BridgeEnabled
	}
	if !isNil(o.LocationAnalyticsEnabled) {
		toSerialize["locationAnalyticsEnabled"] = o.LocationAnalyticsEnabled
	}
	if !isNil(o.UpgradeStrategy) {
		toSerialize["upgradeStrategy"] = o.UpgradeStrategy
	}
	if !isNil(o.LedLightsOn) {
		toSerialize["ledLightsOn"] = o.LedLightsOn
	}
	if !isNil(o.NamedVlans) {
		toSerialize["namedVlans"] = o.NamedVlans
	}
	if !isNil(o.RegulatoryDomain) {
		toSerialize["regulatoryDomain"] = o.RegulatoryDomain
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200197 struct {
	value *InlineResponse200197
	isSet bool
}

func (v NullableInlineResponse200197) Get() *InlineResponse200197 {
	return v.value
}

func (v *NullableInlineResponse200197) Set(val *InlineResponse200197) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200197) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200197) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200197(val *InlineResponse200197) *NullableInlineResponse200197 {
	return &NullableInlineResponse200197{value: val, isSet: true}
}

func (v NullableInlineResponse200197) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200197) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


