/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 February, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.43.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20044ProductsSwitch The Switch network to be updated
type InlineResponse20044ProductsSwitch struct {
	NextUpgrade *InlineResponse20044ProductsSwitchNextUpgrade `json:"nextUpgrade,omitempty"`
}

// NewInlineResponse20044ProductsSwitch instantiates a new InlineResponse20044ProductsSwitch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20044ProductsSwitch() *InlineResponse20044ProductsSwitch {
	this := InlineResponse20044ProductsSwitch{}
	return &this
}

// NewInlineResponse20044ProductsSwitchWithDefaults instantiates a new InlineResponse20044ProductsSwitch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20044ProductsSwitchWithDefaults() *InlineResponse20044ProductsSwitch {
	this := InlineResponse20044ProductsSwitch{}
	return &this
}

// GetNextUpgrade returns the NextUpgrade field value if set, zero value otherwise.
func (o *InlineResponse20044ProductsSwitch) GetNextUpgrade() InlineResponse20044ProductsSwitchNextUpgrade {
	if o == nil || isNil(o.NextUpgrade) {
		var ret InlineResponse20044ProductsSwitchNextUpgrade
		return ret
	}
	return *o.NextUpgrade
}

// GetNextUpgradeOk returns a tuple with the NextUpgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20044ProductsSwitch) GetNextUpgradeOk() (*InlineResponse20044ProductsSwitchNextUpgrade, bool) {
	if o == nil || isNil(o.NextUpgrade) {
    return nil, false
	}
	return o.NextUpgrade, true
}

// HasNextUpgrade returns a boolean if a field has been set.
func (o *InlineResponse20044ProductsSwitch) HasNextUpgrade() bool {
	if o != nil && !isNil(o.NextUpgrade) {
		return true
	}

	return false
}

// SetNextUpgrade gets a reference to the given InlineResponse20044ProductsSwitchNextUpgrade and assigns it to the NextUpgrade field.
func (o *InlineResponse20044ProductsSwitch) SetNextUpgrade(v InlineResponse20044ProductsSwitchNextUpgrade) {
	o.NextUpgrade = &v
}

func (o InlineResponse20044ProductsSwitch) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.NextUpgrade) {
		toSerialize["nextUpgrade"] = o.NextUpgrade
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20044ProductsSwitch struct {
	value *InlineResponse20044ProductsSwitch
	isSet bool
}

func (v NullableInlineResponse20044ProductsSwitch) Get() *InlineResponse20044ProductsSwitch {
	return v.value
}

func (v *NullableInlineResponse20044ProductsSwitch) Set(val *InlineResponse20044ProductsSwitch) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20044ProductsSwitch) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20044ProductsSwitch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20044ProductsSwitch(val *InlineResponse20044ProductsSwitch) *NullableInlineResponse20044ProductsSwitch {
	return &NullableInlineResponse20044ProductsSwitch{value: val, isSet: true}
}

func (v NullableInlineResponse20044ProductsSwitch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20044ProductsSwitch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


