/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 04 December, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.53.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200338Readings struct for InlineResponse200338Readings
type InlineResponse200338Readings struct {
	// The type of packets being counted
	Name *string `json:"name,omitempty"`
	// The total count of sent and received packets during the timespan
	Total *int32 `json:"total,omitempty"`
	// The total count of packets received by the interface during the timespan
	Recv *int32 `json:"recv,omitempty"`
	// The total count of packets sent by the interface during the timespan
	Send *int32 `json:"send,omitempty"`
	Rate *InlineResponse200338Rate `json:"rate,omitempty"`
}

// NewInlineResponse200338Readings instantiates a new InlineResponse200338Readings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200338Readings() *InlineResponse200338Readings {
	this := InlineResponse200338Readings{}
	return &this
}

// NewInlineResponse200338ReadingsWithDefaults instantiates a new InlineResponse200338Readings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200338ReadingsWithDefaults() *InlineResponse200338Readings {
	this := InlineResponse200338Readings{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InlineResponse200338Readings) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200338Readings) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InlineResponse200338Readings) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InlineResponse200338Readings) SetName(v string) {
	o.Name = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *InlineResponse200338Readings) GetTotal() int32 {
	if o == nil || isNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200338Readings) GetTotalOk() (*int32, bool) {
	if o == nil || isNil(o.Total) {
    return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *InlineResponse200338Readings) HasTotal() bool {
	if o != nil && !isNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *InlineResponse200338Readings) SetTotal(v int32) {
	o.Total = &v
}

// GetRecv returns the Recv field value if set, zero value otherwise.
func (o *InlineResponse200338Readings) GetRecv() int32 {
	if o == nil || isNil(o.Recv) {
		var ret int32
		return ret
	}
	return *o.Recv
}

// GetRecvOk returns a tuple with the Recv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200338Readings) GetRecvOk() (*int32, bool) {
	if o == nil || isNil(o.Recv) {
    return nil, false
	}
	return o.Recv, true
}

// HasRecv returns a boolean if a field has been set.
func (o *InlineResponse200338Readings) HasRecv() bool {
	if o != nil && !isNil(o.Recv) {
		return true
	}

	return false
}

// SetRecv gets a reference to the given int32 and assigns it to the Recv field.
func (o *InlineResponse200338Readings) SetRecv(v int32) {
	o.Recv = &v
}

// GetSend returns the Send field value if set, zero value otherwise.
func (o *InlineResponse200338Readings) GetSend() int32 {
	if o == nil || isNil(o.Send) {
		var ret int32
		return ret
	}
	return *o.Send
}

// GetSendOk returns a tuple with the Send field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200338Readings) GetSendOk() (*int32, bool) {
	if o == nil || isNil(o.Send) {
    return nil, false
	}
	return o.Send, true
}

// HasSend returns a boolean if a field has been set.
func (o *InlineResponse200338Readings) HasSend() bool {
	if o != nil && !isNil(o.Send) {
		return true
	}

	return false
}

// SetSend gets a reference to the given int32 and assigns it to the Send field.
func (o *InlineResponse200338Readings) SetSend(v int32) {
	o.Send = &v
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *InlineResponse200338Readings) GetRate() InlineResponse200338Rate {
	if o == nil || isNil(o.Rate) {
		var ret InlineResponse200338Rate
		return ret
	}
	return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200338Readings) GetRateOk() (*InlineResponse200338Rate, bool) {
	if o == nil || isNil(o.Rate) {
    return nil, false
	}
	return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *InlineResponse200338Readings) HasRate() bool {
	if o != nil && !isNil(o.Rate) {
		return true
	}

	return false
}

// SetRate gets a reference to the given InlineResponse200338Rate and assigns it to the Rate field.
func (o *InlineResponse200338Readings) SetRate(v InlineResponse200338Rate) {
	o.Rate = &v
}

func (o InlineResponse200338Readings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !isNil(o.Recv) {
		toSerialize["recv"] = o.Recv
	}
	if !isNil(o.Send) {
		toSerialize["send"] = o.Send
	}
	if !isNil(o.Rate) {
		toSerialize["rate"] = o.Rate
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200338Readings struct {
	value *InlineResponse200338Readings
	isSet bool
}

func (v NullableInlineResponse200338Readings) Get() *InlineResponse200338Readings {
	return v.value
}

func (v *NullableInlineResponse200338Readings) Set(val *InlineResponse200338Readings) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200338Readings) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200338Readings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200338Readings(val *InlineResponse200338Readings) *NullableInlineResponse200338Readings {
	return &NullableInlineResponse200338Readings{value: val, isSet: true}
}

func (v NullableInlineResponse200338Readings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200338Readings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


