/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 04 March, 2026 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.68.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200341Routing Routing configuration for the site
type InlineResponse200341Routing struct {
	DefaultRoute *InlineResponse200341RoutingDefaultRoute `json:"defaultRoute,omitempty"`
}

// NewInlineResponse200341Routing instantiates a new InlineResponse200341Routing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200341Routing() *InlineResponse200341Routing {
	this := InlineResponse200341Routing{}
	return &this
}

// NewInlineResponse200341RoutingWithDefaults instantiates a new InlineResponse200341Routing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200341RoutingWithDefaults() *InlineResponse200341Routing {
	this := InlineResponse200341Routing{}
	return &this
}

// GetDefaultRoute returns the DefaultRoute field value if set, zero value otherwise.
func (o *InlineResponse200341Routing) GetDefaultRoute() InlineResponse200341RoutingDefaultRoute {
	if o == nil || isNil(o.DefaultRoute) {
		var ret InlineResponse200341RoutingDefaultRoute
		return ret
	}
	return *o.DefaultRoute
}

// GetDefaultRouteOk returns a tuple with the DefaultRoute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200341Routing) GetDefaultRouteOk() (*InlineResponse200341RoutingDefaultRoute, bool) {
	if o == nil || isNil(o.DefaultRoute) {
    return nil, false
	}
	return o.DefaultRoute, true
}

// HasDefaultRoute returns a boolean if a field has been set.
func (o *InlineResponse200341Routing) HasDefaultRoute() bool {
	if o != nil && !isNil(o.DefaultRoute) {
		return true
	}

	return false
}

// SetDefaultRoute gets a reference to the given InlineResponse200341RoutingDefaultRoute and assigns it to the DefaultRoute field.
func (o *InlineResponse200341Routing) SetDefaultRoute(v InlineResponse200341RoutingDefaultRoute) {
	o.DefaultRoute = &v
}

func (o InlineResponse200341Routing) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.DefaultRoute) {
		toSerialize["defaultRoute"] = o.DefaultRoute
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200341Routing struct {
	value *InlineResponse200341Routing
	isSet bool
}

func (v NullableInlineResponse200341Routing) Get() *InlineResponse200341Routing {
	return v.value
}

func (v *NullableInlineResponse200341Routing) Set(val *InlineResponse200341Routing) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200341Routing) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200341Routing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200341Routing(val *InlineResponse200341Routing) *NullableInlineResponse200341Routing {
	return &NullableInlineResponse200341Routing{value: val, isSet: true}
}

func (v NullableInlineResponse200341Routing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200341Routing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


