/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 June, 2022 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.22.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject26 struct for InlineObject26
type InlineObject26 struct {
	// A list of URL patterns that are allowed
	AllowedUrlPatterns *[]string `json:"allowedUrlPatterns,omitempty"`
	// A list of URL patterns that are blocked
	BlockedUrlPatterns *[]string `json:"blockedUrlPatterns,omitempty"`
	// A list of URL categories to block
	BlockedUrlCategories *[]string `json:"blockedUrlCategories,omitempty"`
	// URL category list size which is either 'topSites' or 'fullList'
	UrlCategoryListSize *string `json:"urlCategoryListSize,omitempty"`
}

// NewInlineObject26 instantiates a new InlineObject26 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject26() *InlineObject26 {
	this := InlineObject26{}
	return &this
}

// NewInlineObject26WithDefaults instantiates a new InlineObject26 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject26WithDefaults() *InlineObject26 {
	this := InlineObject26{}
	return &this
}

// GetAllowedUrlPatterns returns the AllowedUrlPatterns field value if set, zero value otherwise.
func (o *InlineObject26) GetAllowedUrlPatterns() []string {
	if o == nil || o.AllowedUrlPatterns == nil {
		var ret []string
		return ret
	}
	return *o.AllowedUrlPatterns
}

// GetAllowedUrlPatternsOk returns a tuple with the AllowedUrlPatterns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject26) GetAllowedUrlPatternsOk() (*[]string, bool) {
	if o == nil || o.AllowedUrlPatterns == nil {
		return nil, false
	}
	return o.AllowedUrlPatterns, true
}

// HasAllowedUrlPatterns returns a boolean if a field has been set.
func (o *InlineObject26) HasAllowedUrlPatterns() bool {
	if o != nil && o.AllowedUrlPatterns != nil {
		return true
	}

	return false
}

// SetAllowedUrlPatterns gets a reference to the given []string and assigns it to the AllowedUrlPatterns field.
func (o *InlineObject26) SetAllowedUrlPatterns(v []string) {
	o.AllowedUrlPatterns = &v
}

// GetBlockedUrlPatterns returns the BlockedUrlPatterns field value if set, zero value otherwise.
func (o *InlineObject26) GetBlockedUrlPatterns() []string {
	if o == nil || o.BlockedUrlPatterns == nil {
		var ret []string
		return ret
	}
	return *o.BlockedUrlPatterns
}

// GetBlockedUrlPatternsOk returns a tuple with the BlockedUrlPatterns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject26) GetBlockedUrlPatternsOk() (*[]string, bool) {
	if o == nil || o.BlockedUrlPatterns == nil {
		return nil, false
	}
	return o.BlockedUrlPatterns, true
}

// HasBlockedUrlPatterns returns a boolean if a field has been set.
func (o *InlineObject26) HasBlockedUrlPatterns() bool {
	if o != nil && o.BlockedUrlPatterns != nil {
		return true
	}

	return false
}

// SetBlockedUrlPatterns gets a reference to the given []string and assigns it to the BlockedUrlPatterns field.
func (o *InlineObject26) SetBlockedUrlPatterns(v []string) {
	o.BlockedUrlPatterns = &v
}

// GetBlockedUrlCategories returns the BlockedUrlCategories field value if set, zero value otherwise.
func (o *InlineObject26) GetBlockedUrlCategories() []string {
	if o == nil || o.BlockedUrlCategories == nil {
		var ret []string
		return ret
	}
	return *o.BlockedUrlCategories
}

// GetBlockedUrlCategoriesOk returns a tuple with the BlockedUrlCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject26) GetBlockedUrlCategoriesOk() (*[]string, bool) {
	if o == nil || o.BlockedUrlCategories == nil {
		return nil, false
	}
	return o.BlockedUrlCategories, true
}

// HasBlockedUrlCategories returns a boolean if a field has been set.
func (o *InlineObject26) HasBlockedUrlCategories() bool {
	if o != nil && o.BlockedUrlCategories != nil {
		return true
	}

	return false
}

// SetBlockedUrlCategories gets a reference to the given []string and assigns it to the BlockedUrlCategories field.
func (o *InlineObject26) SetBlockedUrlCategories(v []string) {
	o.BlockedUrlCategories = &v
}

// GetUrlCategoryListSize returns the UrlCategoryListSize field value if set, zero value otherwise.
func (o *InlineObject26) GetUrlCategoryListSize() string {
	if o == nil || o.UrlCategoryListSize == nil {
		var ret string
		return ret
	}
	return *o.UrlCategoryListSize
}

// GetUrlCategoryListSizeOk returns a tuple with the UrlCategoryListSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject26) GetUrlCategoryListSizeOk() (*string, bool) {
	if o == nil || o.UrlCategoryListSize == nil {
		return nil, false
	}
	return o.UrlCategoryListSize, true
}

// HasUrlCategoryListSize returns a boolean if a field has been set.
func (o *InlineObject26) HasUrlCategoryListSize() bool {
	if o != nil && o.UrlCategoryListSize != nil {
		return true
	}

	return false
}

// SetUrlCategoryListSize gets a reference to the given string and assigns it to the UrlCategoryListSize field.
func (o *InlineObject26) SetUrlCategoryListSize(v string) {
	o.UrlCategoryListSize = &v
}

func (o InlineObject26) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowedUrlPatterns != nil {
		toSerialize["allowedUrlPatterns"] = o.AllowedUrlPatterns
	}
	if o.BlockedUrlPatterns != nil {
		toSerialize["blockedUrlPatterns"] = o.BlockedUrlPatterns
	}
	if o.BlockedUrlCategories != nil {
		toSerialize["blockedUrlCategories"] = o.BlockedUrlCategories
	}
	if o.UrlCategoryListSize != nil {
		toSerialize["urlCategoryListSize"] = o.UrlCategoryListSize
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject26 struct {
	value *InlineObject26
	isSet bool
}

func (v NullableInlineObject26) Get() *InlineObject26 {
	return v.value
}

func (v *NullableInlineObject26) Set(val *InlineObject26) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject26) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject26) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject26(val *InlineObject26) *NullableInlineObject26 {
	return &NullableInlineObject26{value: val, isSet: true}
}

func (v NullableInlineObject26) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject26) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


