/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 March, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.56.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200350Items struct for InlineResponse200350Items
type InlineResponse200350Items struct {
	// The cloud ID of the wireless LAN controller
	Serial *string `json:"serial,omitempty"`
	// Layer 2 interfaces belongs to the wireless LAN controller
	Interfaces []InlineResponse200350Interfaces `json:"interfaces,omitempty"`
}

// NewInlineResponse200350Items instantiates a new InlineResponse200350Items object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200350Items() *InlineResponse200350Items {
	this := InlineResponse200350Items{}
	return &this
}

// NewInlineResponse200350ItemsWithDefaults instantiates a new InlineResponse200350Items object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200350ItemsWithDefaults() *InlineResponse200350Items {
	this := InlineResponse200350Items{}
	return &this
}

// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *InlineResponse200350Items) GetSerial() string {
	if o == nil || isNil(o.Serial) {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200350Items) GetSerialOk() (*string, bool) {
	if o == nil || isNil(o.Serial) {
    return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *InlineResponse200350Items) HasSerial() bool {
	if o != nil && !isNil(o.Serial) {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *InlineResponse200350Items) SetSerial(v string) {
	o.Serial = &v
}

// GetInterfaces returns the Interfaces field value if set, zero value otherwise.
func (o *InlineResponse200350Items) GetInterfaces() []InlineResponse200350Interfaces {
	if o == nil || isNil(o.Interfaces) {
		var ret []InlineResponse200350Interfaces
		return ret
	}
	return o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200350Items) GetInterfacesOk() ([]InlineResponse200350Interfaces, bool) {
	if o == nil || isNil(o.Interfaces) {
    return nil, false
	}
	return o.Interfaces, true
}

// HasInterfaces returns a boolean if a field has been set.
func (o *InlineResponse200350Items) HasInterfaces() bool {
	if o != nil && !isNil(o.Interfaces) {
		return true
	}

	return false
}

// SetInterfaces gets a reference to the given []InlineResponse200350Interfaces and assigns it to the Interfaces field.
func (o *InlineResponse200350Items) SetInterfaces(v []InlineResponse200350Interfaces) {
	o.Interfaces = v
}

func (o InlineResponse200350Items) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Serial) {
		toSerialize["serial"] = o.Serial
	}
	if !isNil(o.Interfaces) {
		toSerialize["interfaces"] = o.Interfaces
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200350Items struct {
	value *InlineResponse200350Items
	isSet bool
}

func (v NullableInlineResponse200350Items) Get() *InlineResponse200350Items {
	return v.value
}

func (v *NullableInlineResponse200350Items) Set(val *InlineResponse200350Items) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200350Items) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200350Items) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200350Items(val *InlineResponse200350Items) *NullableInlineResponse200350Items {
	return &NullableInlineResponse200350Items{value: val, isSet: true}
}

func (v NullableInlineResponse200350Items) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200350Items) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


