/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 May, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.58.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200358Meta Other metadata related to this result set.
type InlineResponse200358Meta struct {
	Counts *InlineResponse200358MetaCounts `json:"counts,omitempty"`
}

// NewInlineResponse200358Meta instantiates a new InlineResponse200358Meta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200358Meta() *InlineResponse200358Meta {
	this := InlineResponse200358Meta{}
	return &this
}

// NewInlineResponse200358MetaWithDefaults instantiates a new InlineResponse200358Meta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200358MetaWithDefaults() *InlineResponse200358Meta {
	this := InlineResponse200358Meta{}
	return &this
}

// GetCounts returns the Counts field value if set, zero value otherwise.
func (o *InlineResponse200358Meta) GetCounts() InlineResponse200358MetaCounts {
	if o == nil || isNil(o.Counts) {
		var ret InlineResponse200358MetaCounts
		return ret
	}
	return *o.Counts
}

// GetCountsOk returns a tuple with the Counts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200358Meta) GetCountsOk() (*InlineResponse200358MetaCounts, bool) {
	if o == nil || isNil(o.Counts) {
    return nil, false
	}
	return o.Counts, true
}

// HasCounts returns a boolean if a field has been set.
func (o *InlineResponse200358Meta) HasCounts() bool {
	if o != nil && !isNil(o.Counts) {
		return true
	}

	return false
}

// SetCounts gets a reference to the given InlineResponse200358MetaCounts and assigns it to the Counts field.
func (o *InlineResponse200358Meta) SetCounts(v InlineResponse200358MetaCounts) {
	o.Counts = &v
}

func (o InlineResponse200358Meta) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Counts) {
		toSerialize["counts"] = o.Counts
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200358Meta struct {
	value *InlineResponse200358Meta
	isSet bool
}

func (v NullableInlineResponse200358Meta) Get() *InlineResponse200358Meta {
	return v.value
}

func (v *NullableInlineResponse200358Meta) Set(val *InlineResponse200358Meta) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200358Meta) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200358Meta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200358Meta(val *InlineResponse200358Meta) *NullableInlineResponse200358Meta {
	return &NullableInlineResponse200358Meta{value: val, isSet: true}
}

func (v NullableInlineResponse200358Meta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200358Meta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


