/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 February, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.43.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject226 struct for InlineObject226
type InlineObject226 struct {
	// A set of devices to import (or update)
	Devices []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices `json:"devices"`
}

// NewInlineObject226 instantiates a new InlineObject226 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject226(devices []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices) *InlineObject226 {
	this := InlineObject226{}
	this.Devices = devices
	return &this
}

// NewInlineObject226WithDefaults instantiates a new InlineObject226 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject226WithDefaults() *InlineObject226 {
	this := InlineObject226{}
	return &this
}

// GetDevices returns the Devices field value
func (o *InlineObject226) GetDevices() []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices {
	if o == nil {
		var ret []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices
		return ret
	}

	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value
// and a boolean to check if the value has been set.
func (o *InlineObject226) GetDevicesOk() ([]OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices, bool) {
	if o == nil {
    return nil, false
	}
	return o.Devices, true
}

// SetDevices sets field value
func (o *InlineObject226) SetDevices(v []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices) {
	o.Devices = v
}

func (o InlineObject226) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["devices"] = o.Devices
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject226 struct {
	value *InlineObject226
	isSet bool
}

func (v NullableInlineObject226) Get() *InlineObject226 {
	return v.value
}

func (v *NullableInlineObject226) Set(val *InlineObject226) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject226) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject226) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject226(val *InlineObject226) *NullableInlineObject226 {
	return &NullableInlineObject226{value: val, isSet: true}
}

func (v NullableInlineObject226) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject226) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


