/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 04 June, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.59.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 struct for NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1
type NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 struct {
	// Serial number of the switch.
	Serial string `json:"serial"`
	// Port identifier of switch port. For modules, the identifier is \"SlotNumber_ModuleType_PortNumber\" (Ex: \"1_8X10G_1\"), otherwise it is just the port number (Ex: \"8\").
	PortId string `json:"portId"`
}

// NewNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 instantiates a new NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1(serial string, portId string) *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 {
	this := NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1{}
	this.Serial = serial
	this.PortId = portId
	return &this
}

// NewNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1WithDefaults instantiates a new NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1WithDefaults() *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 {
	this := NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1{}
	return &this
}

// GetSerial returns the Serial field value
func (o *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) GetSerial() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Serial
}

// GetSerialOk returns a tuple with the Serial field value
// and a boolean to check if the value has been set.
func (o *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) GetSerialOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Serial, true
}

// SetSerial sets field value
func (o *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) SetSerial(v string) {
	o.Serial = v
}

// GetPortId returns the PortId field value
func (o *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) GetPortId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PortId
}

// GetPortIdOk returns a tuple with the PortId field value
// and a boolean to check if the value has been set.
func (o *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) GetPortIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.PortId, true
}

// SetPortId sets field value
func (o *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) SetPortId(v string) {
	o.PortId = v
}

func (o NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["serial"] = o.Serial
	}
	if true {
		toSerialize["portId"] = o.PortId
	}
	return json.Marshal(toSerialize)
}

type NullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 struct {
	value *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1
	isSet bool
}

func (v NullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) Get() *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 {
	return v.value
}

func (v *NullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) Set(val *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1(val *NetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) *NullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1 {
	return &NullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1{value: val, isSet: true}
}

func (v NullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworksNetworkIdSwitchLinkAggregationsSwitchPorts1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


