/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 04 February, 2026 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.67.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject275 struct for InlineObject275
type InlineObject275 struct {
	// List of replacments to perform
	Swaps []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps `json:"swaps"`
}

// NewInlineObject275 instantiates a new InlineObject275 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject275(swaps []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps) *InlineObject275 {
	this := InlineObject275{}
	this.Swaps = swaps
	return &this
}

// NewInlineObject275WithDefaults instantiates a new InlineObject275 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject275WithDefaults() *InlineObject275 {
	this := InlineObject275{}
	return &this
}

// GetSwaps returns the Swaps field value
func (o *InlineObject275) GetSwaps() []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps {
	if o == nil {
		var ret []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps
		return ret
	}

	return o.Swaps
}

// GetSwapsOk returns a tuple with the Swaps field value
// and a boolean to check if the value has been set.
func (o *InlineObject275) GetSwapsOk() ([]OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps, bool) {
	if o == nil {
    return nil, false
	}
	return o.Swaps, true
}

// SetSwaps sets field value
func (o *InlineObject275) SetSwaps(v []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps) {
	o.Swaps = v
}

func (o InlineObject275) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["swaps"] = o.Swaps
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject275 struct {
	value *InlineObject275
	isSet bool
}

func (v NullableInlineObject275) Get() *InlineObject275 {
	return v.value
}

func (v *NullableInlineObject275) Set(val *InlineObject275) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject275) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject275) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject275(val *InlineObject275) *NullableInlineObject275 {
	return &NullableInlineObject275{value: val, isSet: true}
}

func (v NullableInlineObject275) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject275) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


