/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 04 September, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.50.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject242 struct for InlineObject242
type InlineObject242 struct {
	// A set of devices to import (or update)
	Devices []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices `json:"devices"`
}

// NewInlineObject242 instantiates a new InlineObject242 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject242(devices []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices) *InlineObject242 {
	this := InlineObject242{}
	this.Devices = devices
	return &this
}

// NewInlineObject242WithDefaults instantiates a new InlineObject242 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject242WithDefaults() *InlineObject242 {
	this := InlineObject242{}
	return &this
}

// GetDevices returns the Devices field value
func (o *InlineObject242) GetDevices() []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices {
	if o == nil {
		var ret []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices
		return ret
	}

	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value
// and a boolean to check if the value has been set.
func (o *InlineObject242) GetDevicesOk() ([]OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices, bool) {
	if o == nil {
    return nil, false
	}
	return o.Devices, true
}

// SetDevices sets field value
func (o *InlineObject242) SetDevices(v []OrganizationsOrganizationIdInventoryOnboardingCloudMonitoringPrepareDevices) {
	o.Devices = v
}

func (o InlineObject242) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["devices"] = o.Devices
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject242 struct {
	value *InlineObject242
	isSet bool
}

func (v NullableInlineObject242) Get() *InlineObject242 {
	return v.value
}

func (v *NullableInlineObject242) Set(val *InlineObject242) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject242) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject242) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject242(val *InlineObject242) *NullableInlineObject242 {
	return &NullableInlineObject242{value: val, isSet: true}
}

func (v NullableInlineObject242) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject242) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


