/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 July, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.60.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200381Failover Wireless LAN controller failover information
type InlineResponse200381Failover struct {
	Last *InlineResponse200381FailoverLast `json:"last,omitempty"`
	Counts *InlineResponse200381FailoverCounts `json:"counts,omitempty"`
}

// NewInlineResponse200381Failover instantiates a new InlineResponse200381Failover object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200381Failover() *InlineResponse200381Failover {
	this := InlineResponse200381Failover{}
	return &this
}

// NewInlineResponse200381FailoverWithDefaults instantiates a new InlineResponse200381Failover object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200381FailoverWithDefaults() *InlineResponse200381Failover {
	this := InlineResponse200381Failover{}
	return &this
}

// GetLast returns the Last field value if set, zero value otherwise.
func (o *InlineResponse200381Failover) GetLast() InlineResponse200381FailoverLast {
	if o == nil || isNil(o.Last) {
		var ret InlineResponse200381FailoverLast
		return ret
	}
	return *o.Last
}

// GetLastOk returns a tuple with the Last field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200381Failover) GetLastOk() (*InlineResponse200381FailoverLast, bool) {
	if o == nil || isNil(o.Last) {
    return nil, false
	}
	return o.Last, true
}

// HasLast returns a boolean if a field has been set.
func (o *InlineResponse200381Failover) HasLast() bool {
	if o != nil && !isNil(o.Last) {
		return true
	}

	return false
}

// SetLast gets a reference to the given InlineResponse200381FailoverLast and assigns it to the Last field.
func (o *InlineResponse200381Failover) SetLast(v InlineResponse200381FailoverLast) {
	o.Last = &v
}

// GetCounts returns the Counts field value if set, zero value otherwise.
func (o *InlineResponse200381Failover) GetCounts() InlineResponse200381FailoverCounts {
	if o == nil || isNil(o.Counts) {
		var ret InlineResponse200381FailoverCounts
		return ret
	}
	return *o.Counts
}

// GetCountsOk returns a tuple with the Counts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200381Failover) GetCountsOk() (*InlineResponse200381FailoverCounts, bool) {
	if o == nil || isNil(o.Counts) {
    return nil, false
	}
	return o.Counts, true
}

// HasCounts returns a boolean if a field has been set.
func (o *InlineResponse200381Failover) HasCounts() bool {
	if o != nil && !isNil(o.Counts) {
		return true
	}

	return false
}

// SetCounts gets a reference to the given InlineResponse200381FailoverCounts and assigns it to the Counts field.
func (o *InlineResponse200381Failover) SetCounts(v InlineResponse200381FailoverCounts) {
	o.Counts = &v
}

func (o InlineResponse200381Failover) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Last) {
		toSerialize["last"] = o.Last
	}
	if !isNil(o.Counts) {
		toSerialize["counts"] = o.Counts
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200381Failover struct {
	value *InlineResponse200381Failover
	isSet bool
}

func (v NullableInlineResponse200381Failover) Get() *InlineResponse200381Failover {
	return v.value
}

func (v *NullableInlineResponse200381Failover) Set(val *InlineResponse200381Failover) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200381Failover) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200381Failover) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200381Failover(val *InlineResponse200381Failover) *NullableInlineResponse200381Failover {
	return &NullableInlineResponse200381Failover{value: val, isSet: true}
}

func (v NullableInlineResponse200381Failover) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200381Failover) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


