/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 October, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.63.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200307StatesUnused Data for unused licenses
type InlineResponse200307StatesUnused struct {
	// The number of unused licenses
	Count *int32 `json:"count,omitempty"`
	SoonestActivation *InlineResponse200307StatesUnusedSoonestActivation `json:"soonestActivation,omitempty"`
}

// NewInlineResponse200307StatesUnused instantiates a new InlineResponse200307StatesUnused object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200307StatesUnused() *InlineResponse200307StatesUnused {
	this := InlineResponse200307StatesUnused{}
	return &this
}

// NewInlineResponse200307StatesUnusedWithDefaults instantiates a new InlineResponse200307StatesUnused object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200307StatesUnusedWithDefaults() *InlineResponse200307StatesUnused {
	this := InlineResponse200307StatesUnused{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *InlineResponse200307StatesUnused) GetCount() int32 {
	if o == nil || isNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200307StatesUnused) GetCountOk() (*int32, bool) {
	if o == nil || isNil(o.Count) {
    return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *InlineResponse200307StatesUnused) HasCount() bool {
	if o != nil && !isNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *InlineResponse200307StatesUnused) SetCount(v int32) {
	o.Count = &v
}

// GetSoonestActivation returns the SoonestActivation field value if set, zero value otherwise.
func (o *InlineResponse200307StatesUnused) GetSoonestActivation() InlineResponse200307StatesUnusedSoonestActivation {
	if o == nil || isNil(o.SoonestActivation) {
		var ret InlineResponse200307StatesUnusedSoonestActivation
		return ret
	}
	return *o.SoonestActivation
}

// GetSoonestActivationOk returns a tuple with the SoonestActivation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200307StatesUnused) GetSoonestActivationOk() (*InlineResponse200307StatesUnusedSoonestActivation, bool) {
	if o == nil || isNil(o.SoonestActivation) {
    return nil, false
	}
	return o.SoonestActivation, true
}

// HasSoonestActivation returns a boolean if a field has been set.
func (o *InlineResponse200307StatesUnused) HasSoonestActivation() bool {
	if o != nil && !isNil(o.SoonestActivation) {
		return true
	}

	return false
}

// SetSoonestActivation gets a reference to the given InlineResponse200307StatesUnusedSoonestActivation and assigns it to the SoonestActivation field.
func (o *InlineResponse200307StatesUnused) SetSoonestActivation(v InlineResponse200307StatesUnusedSoonestActivation) {
	o.SoonestActivation = &v
}

func (o InlineResponse200307StatesUnused) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !isNil(o.SoonestActivation) {
		toSerialize["soonestActivation"] = o.SoonestActivation
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200307StatesUnused struct {
	value *InlineResponse200307StatesUnused
	isSet bool
}

func (v NullableInlineResponse200307StatesUnused) Get() *InlineResponse200307StatesUnused {
	return v.value
}

func (v *NullableInlineResponse200307StatesUnused) Set(val *InlineResponse200307StatesUnused) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200307StatesUnused) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200307StatesUnused) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200307StatesUnused(val *InlineResponse200307StatesUnused) *NullableInlineResponse200307StatesUnused {
	return &NullableInlineResponse200307StatesUnused{value: val, isSet: true}
}

func (v NullableInlineResponse200307StatesUnused) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200307StatesUnused) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


