/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 04 September, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.50.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject239 struct for InlineObject239
type InlineObject239 struct {
	// List of replacments to perform
	Swaps []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps `json:"swaps"`
}

// NewInlineObject239 instantiates a new InlineObject239 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject239(swaps []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps) *InlineObject239 {
	this := InlineObject239{}
	this.Swaps = swaps
	return &this
}

// NewInlineObject239WithDefaults instantiates a new InlineObject239 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject239WithDefaults() *InlineObject239 {
	this := InlineObject239{}
	return &this
}

// GetSwaps returns the Swaps field value
func (o *InlineObject239) GetSwaps() []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps {
	if o == nil {
		var ret []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps
		return ret
	}

	return o.Swaps
}

// GetSwapsOk returns a tuple with the Swaps field value
// and a boolean to check if the value has been set.
func (o *InlineObject239) GetSwapsOk() ([]OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps, bool) {
	if o == nil {
    return nil, false
	}
	return o.Swaps, true
}

// SetSwaps sets field value
func (o *InlineObject239) SetSwaps(v []OrganizationsOrganizationIdInventoryDevicesSwapsBulkSwaps) {
	o.Swaps = v
}

func (o InlineObject239) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["swaps"] = o.Swaps
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject239 struct {
	value *InlineObject239
	isSet bool
}

func (v NullableInlineObject239) Get() *InlineObject239 {
	return v.value
}

func (v *NullableInlineObject239) Set(val *InlineObject239) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject239) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject239) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject239(val *InlineObject239) *NullableInlineObject239 {
	return &NullableInlineObject239{value: val, isSet: true}
}

func (v NullableInlineObject239) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject239) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


