/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 04 March, 2026 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.68.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// InlineResponse200260Items struct for InlineResponse200260Items
type InlineResponse200260Items struct {
	// Starting datetime of the segment in iso8601 format
	SegmentStart time.Time `json:"segmentStart"`
	Totals InlineResponse200260Totals `json:"totals"`
	// Totals by Type
	ByAlertType []InlineResponse200260ByAlertType `json:"byAlertType"`
}

// NewInlineResponse200260Items instantiates a new InlineResponse200260Items object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200260Items(segmentStart time.Time, totals InlineResponse200260Totals, byAlertType []InlineResponse200260ByAlertType) *InlineResponse200260Items {
	this := InlineResponse200260Items{}
	this.SegmentStart = segmentStart
	this.Totals = totals
	this.ByAlertType = byAlertType
	return &this
}

// NewInlineResponse200260ItemsWithDefaults instantiates a new InlineResponse200260Items object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200260ItemsWithDefaults() *InlineResponse200260Items {
	this := InlineResponse200260Items{}
	return &this
}

// GetSegmentStart returns the SegmentStart field value
func (o *InlineResponse200260Items) GetSegmentStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.SegmentStart
}

// GetSegmentStartOk returns a tuple with the SegmentStart field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200260Items) GetSegmentStartOk() (*time.Time, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SegmentStart, true
}

// SetSegmentStart sets field value
func (o *InlineResponse200260Items) SetSegmentStart(v time.Time) {
	o.SegmentStart = v
}

// GetTotals returns the Totals field value
func (o *InlineResponse200260Items) GetTotals() InlineResponse200260Totals {
	if o == nil {
		var ret InlineResponse200260Totals
		return ret
	}

	return o.Totals
}

// GetTotalsOk returns a tuple with the Totals field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200260Items) GetTotalsOk() (*InlineResponse200260Totals, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Totals, true
}

// SetTotals sets field value
func (o *InlineResponse200260Items) SetTotals(v InlineResponse200260Totals) {
	o.Totals = v
}

// GetByAlertType returns the ByAlertType field value
func (o *InlineResponse200260Items) GetByAlertType() []InlineResponse200260ByAlertType {
	if o == nil {
		var ret []InlineResponse200260ByAlertType
		return ret
	}

	return o.ByAlertType
}

// GetByAlertTypeOk returns a tuple with the ByAlertType field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200260Items) GetByAlertTypeOk() ([]InlineResponse200260ByAlertType, bool) {
	if o == nil {
    return nil, false
	}
	return o.ByAlertType, true
}

// SetByAlertType sets field value
func (o *InlineResponse200260Items) SetByAlertType(v []InlineResponse200260ByAlertType) {
	o.ByAlertType = v
}

func (o InlineResponse200260Items) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["segmentStart"] = o.SegmentStart
	}
	if true {
		toSerialize["totals"] = o.Totals
	}
	if true {
		toSerialize["byAlertType"] = o.ByAlertType
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200260Items struct {
	value *InlineResponse200260Items
	isSet bool
}

func (v NullableInlineResponse200260Items) Get() *InlineResponse200260Items {
	return v.value
}

func (v *NullableInlineResponse200260Items) Set(val *InlineResponse200260Items) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200260Items) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200260Items) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200260Items(val *InlineResponse200260Items) *NullableInlineResponse200260Items {
	return &NullableInlineResponse200260Items{value: val, isSet: true}
}

func (v NullableInlineResponse200260Items) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200260Items) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


