/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 October, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.63.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200393CountsClients Wireless LAN controller client counts
type InlineResponse200393CountsClients struct {
	ByStatus *InlineResponse200393CountsClientsByStatus `json:"byStatus,omitempty"`
}

// NewInlineResponse200393CountsClients instantiates a new InlineResponse200393CountsClients object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200393CountsClients() *InlineResponse200393CountsClients {
	this := InlineResponse200393CountsClients{}
	return &this
}

// NewInlineResponse200393CountsClientsWithDefaults instantiates a new InlineResponse200393CountsClients object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200393CountsClientsWithDefaults() *InlineResponse200393CountsClients {
	this := InlineResponse200393CountsClients{}
	return &this
}

// GetByStatus returns the ByStatus field value if set, zero value otherwise.
func (o *InlineResponse200393CountsClients) GetByStatus() InlineResponse200393CountsClientsByStatus {
	if o == nil || isNil(o.ByStatus) {
		var ret InlineResponse200393CountsClientsByStatus
		return ret
	}
	return *o.ByStatus
}

// GetByStatusOk returns a tuple with the ByStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200393CountsClients) GetByStatusOk() (*InlineResponse200393CountsClientsByStatus, bool) {
	if o == nil || isNil(o.ByStatus) {
    return nil, false
	}
	return o.ByStatus, true
}

// HasByStatus returns a boolean if a field has been set.
func (o *InlineResponse200393CountsClients) HasByStatus() bool {
	if o != nil && !isNil(o.ByStatus) {
		return true
	}

	return false
}

// SetByStatus gets a reference to the given InlineResponse200393CountsClientsByStatus and assigns it to the ByStatus field.
func (o *InlineResponse200393CountsClients) SetByStatus(v InlineResponse200393CountsClientsByStatus) {
	o.ByStatus = &v
}

func (o InlineResponse200393CountsClients) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ByStatus) {
		toSerialize["byStatus"] = o.ByStatus
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200393CountsClients struct {
	value *InlineResponse200393CountsClients
	isSet bool
}

func (v NullableInlineResponse200393CountsClients) Get() *InlineResponse200393CountsClients {
	return v.value
}

func (v *NullableInlineResponse200393CountsClients) Set(val *InlineResponse200393CountsClients) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200393CountsClients) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200393CountsClients) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200393CountsClients(val *InlineResponse200393CountsClients) *NullableInlineResponse200393CountsClients {
	return &NullableInlineResponse200393CountsClients{value: val, isSet: true}
}

func (v NullableInlineResponse200393CountsClients) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200393CountsClients) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


