/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 04 March, 2026 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.68.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject310 struct for InlineObject310
type InlineObject310 struct {
	// List of zero touch deployments to create
	Items []OrganizationsOrganizationIdWirelessDevicesProvisioningDeploymentsItems1 `json:"items"`
	Meta *InlineResponse200240Meta `json:"meta,omitempty"`
}

// NewInlineObject310 instantiates a new InlineObject310 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject310(items []OrganizationsOrganizationIdWirelessDevicesProvisioningDeploymentsItems1) *InlineObject310 {
	this := InlineObject310{}
	this.Items = items
	return &this
}

// NewInlineObject310WithDefaults instantiates a new InlineObject310 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject310WithDefaults() *InlineObject310 {
	this := InlineObject310{}
	return &this
}

// GetItems returns the Items field value
func (o *InlineObject310) GetItems() []OrganizationsOrganizationIdWirelessDevicesProvisioningDeploymentsItems1 {
	if o == nil {
		var ret []OrganizationsOrganizationIdWirelessDevicesProvisioningDeploymentsItems1
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *InlineObject310) GetItemsOk() ([]OrganizationsOrganizationIdWirelessDevicesProvisioningDeploymentsItems1, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *InlineObject310) SetItems(v []OrganizationsOrganizationIdWirelessDevicesProvisioningDeploymentsItems1) {
	o.Items = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *InlineObject310) GetMeta() InlineResponse200240Meta {
	if o == nil || isNil(o.Meta) {
		var ret InlineResponse200240Meta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject310) GetMetaOk() (*InlineResponse200240Meta, bool) {
	if o == nil || isNil(o.Meta) {
    return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *InlineObject310) HasMeta() bool {
	if o != nil && !isNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given InlineResponse200240Meta and assigns it to the Meta field.
func (o *InlineObject310) SetMeta(v InlineResponse200240Meta) {
	o.Meta = &v
}

func (o InlineObject310) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	if !isNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject310 struct {
	value *InlineObject310
	isSet bool
}

func (v NullableInlineObject310) Get() *InlineObject310 {
	return v.value
}

func (v *NullableInlineObject310) Set(val *InlineObject310) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject310) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject310) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject310(val *InlineObject310) *NullableInlineObject310 {
	return &NullableInlineObject310{value: val, isSet: true}
}

func (v NullableInlineObject310) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject310) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


